// Code generated by ent, DO NOT EDIT.

package image

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the image type in the database.
	Label = "image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFileExtension holds the string denoting the file_extension field in the database.
	FieldFileExtension = "file_extension"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeImageOfUser holds the string denoting the image_of_user edge name in mutations.
	EdgeImageOfUser = "image_of_user"
	// Table holds the table name of the image in the database.
	Table = "images"
	// ImageOfUserTable is the table that holds the image_of_user relation/edge.
	ImageOfUserTable = "images"
	// ImageOfUserInverseTable is the table name for the ImageOfUser entity.
	// It exists in this package in order to avoid circular dependency with the "imageofuser" package.
	ImageOfUserInverseTable = "image_of_users"
	// ImageOfUserColumn is the table column denoting the image_of_user relation/edge.
	ImageOfUserColumn = "image_of_user_image"
)

// Columns holds all SQL columns for image fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeletedAt,
	FieldName,
	FieldFileExtension,
	FieldLocation,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "images"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"image_of_user_image",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// FileExtensionValidator is a validator for the "file_extension" field. It is called by the builders before save.
	FileExtensionValidator func(string) error
	// LocationValidator is a validator for the "location" field. It is called by the builders before save.
	LocationValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
