// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hyeu249/noname-ent-schema/ent/itemhasowner"
	"github.com/Hyeu249/noname-ent-schema/ent/order"
	"github.com/Hyeu249/noname-ent-schema/ent/predicate"
	"github.com/google/uuid"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdateTime sets the "update_time" field.
func (ou *OrderUpdate) SetUpdateTime(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdateTime(t)
	return ou
}

// SetDeletedAt sets the "deleted_at" field.
func (ou *OrderUpdate) SetDeletedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetDeletedAt(t)
	return ou
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDeletedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetDeletedAt(*t)
	}
	return ou
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ou *OrderUpdate) ClearDeletedAt() *OrderUpdate {
	ou.mutation.ClearDeletedAt()
	return ou
}

// SetName sets the "name" field.
func (ou *OrderUpdate) SetName(s string) *OrderUpdate {
	ou.mutation.SetName(s)
	return ou
}

// SetAddress sets the "address" field.
func (ou *OrderUpdate) SetAddress(s string) *OrderUpdate {
	ou.mutation.SetAddress(s)
	return ou
}

// SetPhone sets the "phone" field.
func (ou *OrderUpdate) SetPhone(s string) *OrderUpdate {
	ou.mutation.SetPhone(s)
	return ou
}

// SetEmail sets the "email" field.
func (ou *OrderUpdate) SetEmail(s string) *OrderUpdate {
	ou.mutation.SetEmail(s)
	return ou
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableEmail(s *string) *OrderUpdate {
	if s != nil {
		ou.SetEmail(*s)
	}
	return ou
}

// ClearEmail clears the value of the "email" field.
func (ou *OrderUpdate) ClearEmail() *OrderUpdate {
	ou.mutation.ClearEmail()
	return ou
}

// SetItemHasOwnerID sets the "item_has_owner" edge to the ItemHasOwner entity by ID.
func (ou *OrderUpdate) SetItemHasOwnerID(id uuid.UUID) *OrderUpdate {
	ou.mutation.SetItemHasOwnerID(id)
	return ou
}

// SetItemHasOwner sets the "item_has_owner" edge to the ItemHasOwner entity.
func (ou *OrderUpdate) SetItemHasOwner(i *ItemHasOwner) *OrderUpdate {
	return ou.SetItemHasOwnerID(i.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearItemHasOwner clears the "item_has_owner" edge to the ItemHasOwner entity.
func (ou *OrderUpdate) ClearItemHasOwner() *OrderUpdate {
	ou.mutation.ClearItemHasOwner()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks[int, OrderMutation](ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() {
	if _, ok := ou.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		ou.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.Name(); ok {
		if err := order.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Order.name": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Address(); ok {
		if err := order.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Order.address": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Phone(); ok {
		if err := order.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Order.phone": %w`, err)}
		}
	}
	if _, ok := ou.mutation.ItemHasOwnerID(); ou.mutation.ItemHasOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.item_has_owner"`)
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: order.FieldID,
			},
		},
	}
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if ou.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if value, ok := ou.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ou.mutation.Phone(); ok {
		_spec.SetField(order.FieldPhone, field.TypeString, value)
	}
	if value, ok := ou.mutation.Email(); ok {
		_spec.SetField(order.FieldEmail, field.TypeString, value)
	}
	if ou.mutation.EmailCleared() {
		_spec.ClearField(order.FieldEmail, field.TypeString)
	}
	if ou.mutation.ItemHasOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ItemHasOwnerTable,
			Columns: []string{order.ItemHasOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: itemhasowner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.ItemHasOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ItemHasOwnerTable,
			Columns: []string{order.ItemHasOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: itemhasowner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdateTime sets the "update_time" field.
func (ouo *OrderUpdateOne) SetUpdateTime(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdateTime(t)
	return ouo
}

// SetDeletedAt sets the "deleted_at" field.
func (ouo *OrderUpdateOne) SetDeletedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetDeletedAt(t)
	return ouo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDeletedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetDeletedAt(*t)
	}
	return ouo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ouo *OrderUpdateOne) ClearDeletedAt() *OrderUpdateOne {
	ouo.mutation.ClearDeletedAt()
	return ouo
}

// SetName sets the "name" field.
func (ouo *OrderUpdateOne) SetName(s string) *OrderUpdateOne {
	ouo.mutation.SetName(s)
	return ouo
}

// SetAddress sets the "address" field.
func (ouo *OrderUpdateOne) SetAddress(s string) *OrderUpdateOne {
	ouo.mutation.SetAddress(s)
	return ouo
}

// SetPhone sets the "phone" field.
func (ouo *OrderUpdateOne) SetPhone(s string) *OrderUpdateOne {
	ouo.mutation.SetPhone(s)
	return ouo
}

// SetEmail sets the "email" field.
func (ouo *OrderUpdateOne) SetEmail(s string) *OrderUpdateOne {
	ouo.mutation.SetEmail(s)
	return ouo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableEmail(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetEmail(*s)
	}
	return ouo
}

// ClearEmail clears the value of the "email" field.
func (ouo *OrderUpdateOne) ClearEmail() *OrderUpdateOne {
	ouo.mutation.ClearEmail()
	return ouo
}

// SetItemHasOwnerID sets the "item_has_owner" edge to the ItemHasOwner entity by ID.
func (ouo *OrderUpdateOne) SetItemHasOwnerID(id uuid.UUID) *OrderUpdateOne {
	ouo.mutation.SetItemHasOwnerID(id)
	return ouo
}

// SetItemHasOwner sets the "item_has_owner" edge to the ItemHasOwner entity.
func (ouo *OrderUpdateOne) SetItemHasOwner(i *ItemHasOwner) *OrderUpdateOne {
	return ouo.SetItemHasOwnerID(i.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearItemHasOwner clears the "item_has_owner" edge to the ItemHasOwner entity.
func (ouo *OrderUpdateOne) ClearItemHasOwner() *OrderUpdateOne {
	ouo.mutation.ClearItemHasOwner()
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	ouo.defaults()
	return withHooks[*Order, OrderMutation](ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		ouo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.Name(); ok {
		if err := order.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Order.name": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Address(); ok {
		if err := order.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Order.address": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Phone(); ok {
		if err := order.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Order.phone": %w`, err)}
		}
	}
	if _, ok := ouo.mutation.ItemHasOwnerID(); ouo.mutation.ItemHasOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.item_has_owner"`)
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: order.FieldID,
			},
		},
	}
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if ouo.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Phone(); ok {
		_spec.SetField(order.FieldPhone, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Email(); ok {
		_spec.SetField(order.FieldEmail, field.TypeString, value)
	}
	if ouo.mutation.EmailCleared() {
		_spec.ClearField(order.FieldEmail, field.TypeString)
	}
	if ouo.mutation.ItemHasOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ItemHasOwnerTable,
			Columns: []string{order.ItemHasOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: itemhasowner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.ItemHasOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ItemHasOwnerTable,
			Columns: []string{order.ItemHasOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: itemhasowner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
