// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hyeu249/noname-ent-schema/ent/predicate"
	"github.com/Hyeu249/noname-ent-schema/ent/productquote"
)

// ProductQuoteDelete is the builder for deleting a ProductQuote entity.
type ProductQuoteDelete struct {
	config
	hooks    []Hook
	mutation *ProductQuoteMutation
}

// Where appends a list predicates to the ProductQuoteDelete builder.
func (pqd *ProductQuoteDelete) Where(ps ...predicate.ProductQuote) *ProductQuoteDelete {
	pqd.mutation.Where(ps...)
	return pqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pqd *ProductQuoteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ProductQuoteMutation](ctx, pqd.sqlExec, pqd.mutation, pqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pqd *ProductQuoteDelete) ExecX(ctx context.Context) int {
	n, err := pqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pqd *ProductQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: productquote.FieldID,
			},
		},
	}
	if ps := pqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pqd.mutation.done = true
	return affected, err
}

// ProductQuoteDeleteOne is the builder for deleting a single ProductQuote entity.
type ProductQuoteDeleteOne struct {
	pqd *ProductQuoteDelete
}

// Where appends a list predicates to the ProductQuoteDelete builder.
func (pqdo *ProductQuoteDeleteOne) Where(ps ...predicate.ProductQuote) *ProductQuoteDeleteOne {
	pqdo.pqd.mutation.Where(ps...)
	return pqdo
}

// Exec executes the deletion query.
func (pqdo *ProductQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := pqdo.pqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pqdo *ProductQuoteDeleteOne) ExecX(ctx context.Context) {
	if err := pqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
