// Code generated by ent, DO NOT EDIT.

package imageofuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Hyeu249/noname-ent-schema/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldUpdateTime, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldDeletedAt, v))
}

// Royalty applies equality check predicate on the "royalty" field. It's identical to RoyaltyEQ.
func Royalty(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldRoyalty, v))
}

// IsImagePublished applies equality check predicate on the "is_image_published" field. It's identical to IsImagePublishedEQ.
func IsImagePublished(v bool) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldIsImagePublished, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLTE(FieldUpdateTime, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotNull(FieldDeletedAt))
}

// RoyaltyEQ applies the EQ predicate on the "royalty" field.
func RoyaltyEQ(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldRoyalty, v))
}

// RoyaltyNEQ applies the NEQ predicate on the "royalty" field.
func RoyaltyNEQ(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldRoyalty, v))
}

// RoyaltyIn applies the In predicate on the "royalty" field.
func RoyaltyIn(vs ...float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIn(FieldRoyalty, vs...))
}

// RoyaltyNotIn applies the NotIn predicate on the "royalty" field.
func RoyaltyNotIn(vs ...float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotIn(FieldRoyalty, vs...))
}

// RoyaltyGT applies the GT predicate on the "royalty" field.
func RoyaltyGT(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGT(FieldRoyalty, v))
}

// RoyaltyGTE applies the GTE predicate on the "royalty" field.
func RoyaltyGTE(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldGTE(FieldRoyalty, v))
}

// RoyaltyLT applies the LT predicate on the "royalty" field.
func RoyaltyLT(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLT(FieldRoyalty, v))
}

// RoyaltyLTE applies the LTE predicate on the "royalty" field.
func RoyaltyLTE(v float32) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldLTE(FieldRoyalty, v))
}

// RoyaltyIsNil applies the IsNil predicate on the "royalty" field.
func RoyaltyIsNil() predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldIsNull(FieldRoyalty))
}

// RoyaltyNotNil applies the NotNil predicate on the "royalty" field.
func RoyaltyNotNil() predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNotNull(FieldRoyalty))
}

// IsImagePublishedEQ applies the EQ predicate on the "is_image_published" field.
func IsImagePublishedEQ(v bool) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldEQ(FieldIsImagePublished, v))
}

// IsImagePublishedNEQ applies the NEQ predicate on the "is_image_published" field.
func IsImagePublishedNEQ(v bool) predicate.ImageOfUser {
	return predicate.ImageOfUser(sql.FieldNEQ(FieldIsImagePublished, v))
}

// HasImage applies the HasEdge predicate on the "image" edge.
func HasImage() predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ImageTable, ImageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImageWith applies the HasEdge predicate on the "image" edge with a given conditions (other predicates).
func HasImageWith(preds ...predicate.Image) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ImageInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ImageTable, ImageColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGoods applies the HasEdge predicate on the "goods" edge.
func HasGoods() predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, GoodsTable, GoodsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGoodsWith applies the HasEdge predicate on the "goods" edge with a given conditions (other predicates).
func HasGoodsWith(preds ...predicate.Goods) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(GoodsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, GoodsTable, GoodsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductQuote applies the HasEdge predicate on the "product_quote" edge.
func HasProductQuote() predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ProductQuoteTable, ProductQuoteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductQuoteWith applies the HasEdge predicate on the "product_quote" edge with a given conditions (other predicates).
func HasProductQuoteWith(preds ...predicate.ProductQuote) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProductQuoteInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ProductQuoteTable, ProductQuoteColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageOfUser) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageOfUser) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageOfUser) predicate.ImageOfUser {
	return predicate.ImageOfUser(func(s *sql.Selector) {
		p(s.Not())
	})
}
