// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldHashedPwd holds the string denoting the hashed_pwd field in the database.
	FieldHashedPwd = "hashed_pwd"
	// FieldIsSuperuser holds the string denoting the is_superuser field in the database.
	FieldIsSuperuser = "is_superuser"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// EdgeImageOfUser holds the string denoting the image_of_user edge name in mutations.
	EdgeImageOfUser = "image_of_user"
	// EdgeProductQuote holds the string denoting the product_quote edge name in mutations.
	EdgeProductQuote = "product_quote"
	// EdgeItemHasOwner holds the string denoting the item_has_owner edge name in mutations.
	EdgeItemHasOwner = "item_has_owner"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ImageOfUserTable is the table that holds the image_of_user relation/edge.
	ImageOfUserTable = "image_of_users"
	// ImageOfUserInverseTable is the table name for the ImageOfUser entity.
	// It exists in this package in order to avoid circular dependency with the "imageofuser" package.
	ImageOfUserInverseTable = "image_of_users"
	// ImageOfUserColumn is the table column denoting the image_of_user relation/edge.
	ImageOfUserColumn = "image_of_user_user"
	// ProductQuoteTable is the table that holds the product_quote relation/edge.
	ProductQuoteTable = "product_quotes"
	// ProductQuoteInverseTable is the table name for the ProductQuote entity.
	// It exists in this package in order to avoid circular dependency with the "productquote" package.
	ProductQuoteInverseTable = "product_quotes"
	// ProductQuoteColumn is the table column denoting the product_quote relation/edge.
	ProductQuoteColumn = "product_quote_user"
	// ItemHasOwnerTable is the table that holds the item_has_owner relation/edge.
	ItemHasOwnerTable = "item_has_owners"
	// ItemHasOwnerInverseTable is the table name for the ItemHasOwner entity.
	// It exists in this package in order to avoid circular dependency with the "itemhasowner" package.
	ItemHasOwnerInverseTable = "item_has_owners"
	// ItemHasOwnerColumn is the table column denoting the item_has_owner relation/edge.
	ItemHasOwnerColumn = "item_has_owner_user"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeletedAt,
	FieldUsername,
	FieldIsActive,
	FieldHashedPwd,
	FieldIsSuperuser,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldAddress,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// HashedPwdValidator is a validator for the "hashed_pwd" field. It is called by the builders before save.
	HashedPwdValidator func(string) error
	// DefaultIsSuperuser holds the default value on creation for the "is_superuser" field.
	DefaultIsSuperuser bool
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
