// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Goods is the predicate function for goods builders.
type Goods func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// ImageOfUser is the predicate function for imageofuser builders.
type ImageOfUser func(*sql.Selector)

// ItemHasOwner is the predicate function for itemhasowner builders.
type ItemHasOwner func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// ProductQuote is the predicate function for productquote builders.
type ProductQuote func(*sql.Selector)

// TypeOfGoods is the predicate function for typeofgoods builders.
type TypeOfGoods func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
